#!/bin/bash

# Script Name:                  System Information
# Author:                       Eduardo Ayala
# Date of latest revision:      05/02/2023
# Purpose:                      List Hardware on Ubuntu (Lab PC)

# Get CPU information
echo "=== CPU Information ==="
sudo lshw -class processor| grep -E "product|vendor|physical id|bus info|width"

# Get RAM information
echo "=== RAM Information ==="
sudo lshw -c memory | grep memory -A 3                                          

# Get Display adapter
echo "=== Display adapter ==="
# Description, Product, Vendor, Physical ID, Bus Info
sudo lshw | grep *-display -A 5
# Width, Clock, Capabilities, Resources
sudo lshw | grep *-display -A 12 | head -12 | tail -4

# Get Network adapter
echo "=== Network adapter ==="
sudo lshw -class network | grep -E "description|product|vendor|physical id|bus info|logical name|version|serial|size|capacity|width|clock|capabilities|configuration|resources"

# Get system summary
echo "=== System Summary ==="
sudo lshw -short